m3u:
  max-connections: 10

  sources:
    greenarw_tv_italia:
      description: "Greenarw TV Italia"
      url: https://gist.githubusercontent.com/greenarw/efa4568ed2fa2e53a1aec9073d027243/raw/7a50a2c1643d1548971928aebdd9e906a2043b9f/tv_italia.m3u
      active: true
    threadfin:
      description: "Threadfin TV Italia"
      url: http://dockers.lan:34400/m3u/threadfin.m3u
      active: false
      proxied: false
      threadfin: true

xmltv:
  sources:
    it_dttsat_full:
      description: "DTT SAT Italia Full EPG"
      url: http://116.202.210.205/test/it_dttsat_full.xml
      active: true
    threadfin:
      description: "Threadfin TV Italia EPG"
      url: http://dockers.lan:34400/xmltv/threadfin.xml
      active: false
      threadfin: true




