m3u:
  max-connections: 10

  sources:
    greenarw_tv_italia:
      description: "Greenarw TV Italia"
      url: https://gist.githubusercontent.com/greenarw/efa4568ed2fa2e53a1aec9073d027243/raw/7a50a2c1643d1548971928aebdd9e906a2043b9f/tv_italia.m3u
      active: false

    iptv_org_italiano:
      description: "IPTV Org Italiano"
      alternate: https://github.com/iptv-org/iptv/blob/master/PLAYLISTS.md
      url: https://iptv-org.github.io/iptv/languages/ita.m3u
      active: true


xmltv:
  sources:
    it_dttsat_full:
      description: "DTT SAT Italia Full EPG"
      url: http://116.202.210.205/test/it_dttsat_full.xml
      active: true


tabs:
  Italia:
    include:
      - match: Rai 1
        tvgNo: 1
      - match: Rai 2
        tvgNo: 2
      - match: Rai 3
        tvgNo: 3
      - match: Rete 4
        tvgNo: 4
      - match: Canale 5
        tvgNo: 5
      - match: Italia 1
        tvgNo: 6
      - match: /^LA7$/
        tvgNo: 7
      - match: TV8
        tvgNo: 8
      - match: NOVE
        tvgNo: 9
      - match: La5
        tvgNo: 10
      - match: /^LA7d$/
        tvgNo: 11
      - match: Iris
        tvgNo: 12
      - match: Cielo
        tvgNo: 13
      - match: Rai Movie
        tvgNo: 14
      - match: Rai Premium
        tvgNo: 15
      - match: Rai Storia
        tvgNo: 16
      - match: Rai Sport
        tvgNo: 17
      - match: Rai Scuola
        tvgNo: 18
      - match: 20 Mediaset
        tvgNo: 20
      - match: Mediaset Extra
        tvgNo: 21
      - match: Mediaset Italia
        tvgNo: 22
      - match: GIALLO
        tvgNo: 23
      - match: TOP Crime
        tvgNo: 24
      - match: Twentyseven
        tvgNo: 27
      - match: Cine 34
        tvgNo: 34
      - match: Focus
        tvgNo: 35
      - match: Real Time
        tvgNo: 36
      - match: QVC
        tvgNo: 37
      - match: Warner TV
        tvgNo: 39
      - match: RaiPlay
        tvgNo: 40
      - match: DMAX
        tvgNo: 41
      - match: Italia 53
        tvgNo: 42
      - match: SPORTITALIA
        tvgNo: 43
      - match: SUPERTENNIS
        tvgNo: 44
      - match: VH1
        tvgNo: 45
      - match: ALMA TV
        tvgNo: 47
      - match: TV2000
        tvgNo: 48


  News:
    start: 50
    groups:
      include:
        - match: news
    include:
      - match: Rai News 24
        tvgNo: 50
      - match: TGCOM 24
        tvgNo: 51
      - match: Sky TG24
        tvgNo: 52
      - match: /.*/

  Cartoni:
    start: 200
    include:
      - match: Boing
      - match: K2
      - match: Rai Gulp
      - match: Rai YoYo
      - match: frisbee
      - match: Boing Plus
      - match: Cartoonito
      - match: Super!


  Radio-1:
    temp: true
    properties:
      group: music    
    and: Radio
    include:
      - match: Capital
      - match: Deejay
      - match: m2o
      - match: RDS
      - match: RTL
      - match: zeta
      - match: freccia
      - match: 101
      - match: monte carlo
      - match: 102.5
      - match: 105
      - match: virgin
      - match: italia
      - match: /.*/

  Radio:
    start: 100
    groups:
      include:
        - match: Music

  Pluto:
    start: 400
    include:
      - match: Pluto

  Education:
    start: 600
    groups:
      include:
        - match: Educa
        - match: Documen


  General:
    groups:
      include:
        - match: general

  Altri:
    start: 1000
    missing: true
