services:
  iptv-viewer:
    image: astevani/lightiptv:latest
    build: .
    container_name: iptv-viewer
    restart: unless-stopped
    ports:
      - "${PORT}:3005"
    environment:
      - THREADFIN_M3U_URL=${THREADFIN_M3U_URL}
      - THREADFIN_XMLTV_URL=${THREADFIN_XMLTV_URL}
      - PORT=3005
    volumes:
      - ./iptv/data:/app/app/data
      - ./iptv/cached:/app/app/public/cached
    networks:
      - iptv-network

networks:
  iptv-network:
    driver: bridge
